/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, TestTest as PrismaTestTest } from "@prisma/client";

export class TestTestServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TestTestCountArgs, "select">): Promise<number> {
    return this.prisma.testTest.count(args);
  }

  async testTests(
    args: Prisma.TestTestFindManyArgs
  ): Promise<PrismaTestTest[]> {
    return this.prisma.testTest.findMany(args);
  }
  async testTest(
    args: Prisma.TestTestFindUniqueArgs
  ): Promise<PrismaTestTest | null> {
    return this.prisma.testTest.findUnique(args);
  }
  async createTestTest(
    args: Prisma.TestTestCreateArgs
  ): Promise<PrismaTestTest> {
    return this.prisma.testTest.create(args);
  }
  async updateTestTest(
    args: Prisma.TestTestUpdateArgs
  ): Promise<PrismaTestTest> {
    return this.prisma.testTest.update(args);
  }
  async deleteTestTest(
    args: Prisma.TestTestDeleteArgs
  ): Promise<PrismaTestTest> {
    return this.prisma.testTest.delete(args);
  }
}
