/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TestTestService } from "../testTest.service";
import { TestTestCreateInput } from "./TestTestCreateInput";
import { TestTest } from "./TestTest";
import { TestTestFindManyArgs } from "./TestTestFindManyArgs";
import { TestTestWhereUniqueInput } from "./TestTestWhereUniqueInput";
import { TestTestUpdateInput } from "./TestTestUpdateInput";

export class TestTestControllerBase {
  constructor(protected readonly service: TestTestService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TestTest })
  async createTestTest(
    @common.Body() data: TestTestCreateInput
  ): Promise<TestTest> {
    return await this.service.createTestTest({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TestTest] })
  @ApiNestedQuery(TestTestFindManyArgs)
  async testTests(@common.Req() request: Request): Promise<TestTest[]> {
    const args = plainToClass(TestTestFindManyArgs, request.query);
    return this.service.testTests({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TestTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async testTest(
    @common.Param() params: TestTestWhereUniqueInput
  ): Promise<TestTest | null> {
    const result = await this.service.testTest({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TestTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTestTest(
    @common.Param() params: TestTestWhereUniqueInput,
    @common.Body() data: TestTestUpdateInput
  ): Promise<TestTest | null> {
    try {
      return await this.service.updateTestTest({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TestTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTestTest(
    @common.Param() params: TestTestWhereUniqueInput
  ): Promise<TestTest | null> {
    try {
      return await this.service.deleteTestTest({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
