/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TestTest } from "./TestTest";
import { TestTestCountArgs } from "./TestTestCountArgs";
import { TestTestFindManyArgs } from "./TestTestFindManyArgs";
import { TestTestFindUniqueArgs } from "./TestTestFindUniqueArgs";
import { DeleteTestTestArgs } from "./DeleteTestTestArgs";
import { TestTestService } from "../testTest.service";
@graphql.Resolver(() => TestTest)
export class TestTestResolverBase {
  constructor(protected readonly service: TestTestService) {}

  async _testTestsMeta(
    @graphql.Args() args: TestTestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TestTest])
  async testTests(
    @graphql.Args() args: TestTestFindManyArgs
  ): Promise<TestTest[]> {
    return this.service.testTests(args);
  }

  @graphql.Query(() => TestTest, { nullable: true })
  async testTest(
    @graphql.Args() args: TestTestFindUniqueArgs
  ): Promise<TestTest | null> {
    const result = await this.service.testTest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TestTest)
  async deleteTestTest(
    @graphql.Args() args: DeleteTestTestArgs
  ): Promise<TestTest | null> {
    try {
      return await this.service.deleteTestTest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
